#ifndef _ALTERA_HEADER_H_
#define _ALTERA_HEADER_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'can_test_1' in
 * file '/home/smiljanic997/Documents/can_test_1/can_test_1.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'ctu_canfd_avalon_0', class 'ctu_canfd_avalon'
 * The macros are prefixed with 'CTU_CANFD_AVALON_0_'.
 * The prefix is the slave descriptor.
 */
#define CTU_CANFD_AVALON_0_COMPONENT_TYPE ctu_canfd_avalon
#define CTU_CANFD_AVALON_0_COMPONENT_NAME ctu_canfd_avalon_0
#define CTU_CANFD_AVALON_0_BASE 0x0
#define CTU_CANFD_AVALON_0_SPAN 65536
#define CTU_CANFD_AVALON_0_END 0xffff

/*
 * Macros for device 'pio_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_0_COMPONENT_TYPE altera_avalon_pio
#define PIO_0_COMPONENT_NAME pio_0
#define PIO_0_BASE 0x10000
#define PIO_0_SPAN 16
#define PIO_0_END 0x1000f
#define PIO_0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_0_CAPTURE 0
#define PIO_0_DATA_WIDTH 8
#define PIO_0_DO_TEST_BENCH_WIRING 0
#define PIO_0_DRIVEN_SIM_VALUE 0
#define PIO_0_EDGE_TYPE NONE
#define PIO_0_FREQ 50000000
#define PIO_0_HAS_IN 0
#define PIO_0_HAS_OUT 1
#define PIO_0_HAS_TRI 0
#define PIO_0_IRQ_TYPE NONE
#define PIO_0_RESET_VALUE 0


#endif /* _ALTERA_HEADER_H_ */
